stages:
  - check

variables:
  PYTHONUNBUFFERED: "1"

check:x86_64-trusty-gcc4:
  stage: check
  image: registry.gitlab.gruntech.org/infinit/drake/trusty-ci
  script:
    - pip3 install -r requirements.txt
    - src/bin/drake . --workdir _build
