sudo: required
language: c
compiler: gcc
services:
  - docker
script:
  - cd _build/linux64
  - make tests
  - make check
  - make sample
  - ./src/sample "chiche donne nous tout"
after_success:
  - bash <(curl -s https://codecov.io/bash)
