stages:
  - check
  - containerize

variables:
  PYTHONUNBUFFERED: "1"

before_script:
  - TAG="$(git describe --always)"

check:
  stage: check
  image: registry.gitlab.gruntech.org/infinit/drake/trusty-ci
  script:
    - pip3 install -r requirements.txt coverage
    - src/bin/drake . --workdir _build --coverage=true
    - cd _build && coverage report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

containerize:
  stage: containerize
  image: registry.gitlab.gruntech.org/infinit/drake/trusty-ci
  script:
    - docker build --tag "drake:$TAG" .
    - docker run --rm "drake:$TAG"
  dependencies:
    - check
