language: python
python:
  - "3.4"
install:
  - "pip install -r requirements.txt"
  - "git config --global user.email mefyl@gruntech.org"
  - "git config --global user.name mefyl"
script:
  - tests/test.py
  - cd _build && ./drake //check
